### ISSUE TITLE
Z-index issue

### ISSUE THREAD

**Issue by PatrickStAmant** [zetane/ZetaForge#100]
### Summary:

Modal behind the graph after clicking 'eye' icon.

<img width="1352" alt="issue" src="https://github.com/zetane/ZetaForge/assets/71685808/c56c8465-0f46-437c-bf06-92067e37cbb2">

### Expected behavior:

Modal should be on top

### Actual behavior:

Modal behind the graph after clicking 'eye' icon.

### Steps to reproduce:

1. Run Canny Edge pipeline
2. Click on the Eye icon of the Canny Edge block
3. The modal is seen behind the canvas blocks.

### Zetaforge version:

Present main

### Operating System

Windows

### Logs:

```bash
none
```

**Comment by keonp** [comment]
Resolved with  [F/ws check #107](https://github.com/zetane/ZetaForge/pull/107)
