### ISSUE TITLE
Docs button not pointing to the correct address

### ISSUE THREAD

**Issue by PatrickStAmant** [zetane/ZetaForge#101]
### Summary:

The docs button opens an empty browser page.

![image](https://github.com/zetane/ZetaForge/assets/71685808/9e79c45b-5a15-46d7-933a-6faa012a42eb)

### Expected behavior:

Open https://zetane.com/docs/
Note that the / at the end is important.

### Actual behavior:

Opens zetane/docs/ or https://zetane/docs/

### Steps to reproduce:

Click on the Docs button in the Help menu

### Zetaforge version:

Latest

### Operating System

Windows

### Logs:

```bash
none
```

**Comment by jmagoon** [comment]
Resolved in #107
