### ISSUE TITLE
`computations.py` compilation fails

### ISSUE THREAD

**Issue by FGRCL** [zetane/ZetaForge#91]
### Summary:

When changing the inputs/outputs of a block in the `computations.py` of block. The compilation into the specs fails, this prevents users from changing IO when making custom blocks.
Additionally: 
- The error message has 2 typos
- The toast is hidden underneath the block editor

### Expected behavior:

The compilation should succeed and the IO should be updated properly.

### Actual behavior:

The compilation fails, an error toast is shown, the IO does not update.

### Steps to reproduce:

1. Drop any block into the canvas
2. Open the block editor
3. Edit the `computations.py`
4. Change the IO of the block
5. Activate your new code

### Zetaforge version:

main

### Operating System

Other (specify)

### Other operating system:

Ubuntu

### Logs:

```bash
Not collected
```

**Comment by jmagoon** [comment]
Fixed by #107
